linux_task:
  # only_if: $CIRRUS_RELEASE != ''
  container:
    dockerfile: .ci/linux/Dockerfile
  environment:
    GITHUB_TOKEN: ENCRYPTED[258a73daeb2437816b12d22b9d09bdddccd411608e5e7688bad8a6c607bdc5329526e0607c5deb609dcda74ba5f9af52]
  populate_script: dotnet restore
  build_script: dotnet publish -r linux-x64 -c release
  publish_script: ./scripts/linux-release.sh

windows_task:
  windows_container:
    dockerfile: .ci/windows/Dockerfile
    os_version: 2019
  populate_script: dotnet restore
  build_script: .\scripts\windows-build.bat
  publish_script: .\scripts\windows-publish.bat

macos_task:
  osx_instance:
    image: mojave-base
  populate_script:
    - brew update
    - brew tap caskroom/cask
    - brew cask install dotnet-sdk
    - brew install hub
    - PATH=/usr/local/share/dotnet:$PATH dotnet restore
  build_script:
    - PATH=/usr/local/share/dotnet:$PATH dotnet publish -r osx-x64 -c release
  publish_script: ./scripts/macOS-release.sh